kind: pipeline
name: openitcockpit-agent


steps:
- name: build_linux_packages
  image: localhost:5000/openitcockpit-agent-centos7:latest
  commands:
  - yum -y install python36-devel python36-pip libffi-devel gcc glibc
  - yum -y install ruby-devel gcc make rpm-build rubygems rpm
  - gem install --no-ri --no-rdoc fpm
  - mkdir -p ./public/{packages,binaries}
  - python3 -m venv ./python3-env
  - source ./python3-env/bin/activate
  - ./python3-env/bin/pip3 install -r requirements.txt
  - ./python3-env/bin/python3 ./python3-env/bin/pyinstaller oitc_agent.py --onefile
  - deactivate
  - mv ./dist/oitc_agent ./public/binaries/openitcockpit-agent-python3.linux.bin
  - chmod +x ./public/binaries/openitcockpit-agent-python3.linux.bin
  - cp ./public/binaries/openitcockpit-agent-python3.linux.bin executables
  - ./packages/scripts/build_linux_drone.sh
  - mv openitcockpit-agent*.{deb,rpm} ./public/packages

- name: upload
  image: plugins/s3
  settings:
    bucket: openitcockpit-agent
    source: public/*
    strip_prefix: public/
    target: ./$$BUILD_NUMBER
    recursive: true
    path_style: true
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
    endpoint:
      from_secret: MINIO_SERVER_ADDRESS
